### PR TITLE
RHCLOUD-33951: Update middleware to v2 for service accounts

### PR DESCRIPTION
**Pull request by skarekrow**
## What?
Explain what the change is linking any relevant JIRAs or Issues.

## Why?
Consider what business or engineering goal does this PR achieves.

## How?
Describe how the change is implemented. Any noteable new libaries, APIs, or features.

## Testing
Did you add any tests for the change?

## Anything Else?
Any other notes about the PR that would be useful for the reviewer. 

## Secure Coding Practices Checklist Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Comment by skarekrow** [comment]
Current failures:
```

[Fail] PSK Based Authentication - OrgID as the required tenant Use identity header authentication With valid identity header and no psk headers [It] Should return 200 when the key is correct
/Users/bschneider/Git Repos/redhat/cloud-connector/internal/middlewares/auth_test.go:34

[Fail] Auth Use identity header authentication With valid identity header and no psk headers [It] Should return 200 when the key is correct
/Users/bschneider/Git Repos/redhat/cloud-connector/internal/middlewares/auth_test.go:34

Ran 16 of 16 Specs in 0.002 seconds
```

**Comment by dehort** [comment]
Try this:

```
diff --git internal/middlewares/principal.go internal/middlewares/principal.go
index 690abf6..733f1ca 100644
--- internal/middlewares/principal.go
+++ internal/middlewares/principal.go
@@ -46,8 +46,14 @@ func GetPrincipal(ctx context.Context) (Principal, bool) {
        p, ok := ctx.Value(principalKey).(serviceToServicePrincipal)
        if !ok {
                id := identity.GetIdentity(ctx)
+
+               if id.Identity == (identity.Identity{}) {
+                       return nil, false
+               }
+
                p := identityPrincipal{account: id.Identity.AccountNumber, orgID: id.Identity.OrgID}
-               return p, ok
+
+               return p, true
        }
        return p, ok
 }
```

If the identity is empty, return `false`.  I'm not a huge fan of the empty struct comparison, but that's all that we have available to us I believe.

**Comment by skarekrow** [comment]
> Try this:
> 
> ```
> diff --git internal/middlewares/principal.go internal/middlewares/principal.go
> index 690abf6..733f1ca 100644
> --- internal/middlewares/principal.go
> +++ internal/middlewares/principal.go
> @@ -46,8 +46,14 @@ func GetPrincipal(ctx context.Context) (Principal, bool) {
>         p, ok := ctx.Value(principalKey).(serviceToServicePrincipal)
>         if !ok {
>                 id := identity.GetIdentity(ctx)
> +
> +               if id.Identity == (identity.Identity{}) {
> +                       return nil, false
> +               }
> +
>                 p := identityPrincipal{account: id.Identity.AccountNumber, orgID: id.Identity.OrgID}
> -               return p, ok
> +
> +               return p, true
>         }
>         return p, ok
>  }
> ```
> 
> If the identity is empty, return `false`. I'm not a huge fan of the empty struct comparison, but that's all that we have available to us I believe.

I tested explicitly for 2 empty fields in my commit, lmk what you thin kabout that vs testing against an empty struct

**Review by dehort — APPROVED** [review]
Looks good to me.

I ran some sanity checks in the ephemeral env and it checked out.

I'll merge it shortly.

**Pull request merged**
