### PR TITLE
Inventory integration

### PR DESCRIPTION
**Pull request by dehort**
This is certainly not perfect but it looks like it works in my testing.

I still need to modify it to send the connected client id.  I need to touch base with the inventory team on how they want me to send that.

### CODE REVIEW

**Review by Jason-RH — APPROVED** [review]
LGTM. I'm thinking for consuming these new connections I should just be able to filter the events based on the "cloud-connector" reporter right?

**Comment by Jason-RH** [comment]
@dehort Are you planning on removing hosts from inventory during a disconnection?

**Review by lphiri — APPROVED** [review]
LGTM.

**Comment by dehort** [comment]
@Jason-RH yes, you should be able to look for inventory events with the reporter set to "cloud-connector".

**Pull request merged**
