### PR TITLE
Orgid nonnull field

### PR DESCRIPTION
**Pull request by CodyWMitchell**
## What?
Remove `NOT NULL` from the `account` field and add `NOT NULL` to the `org_id` field.
[RHCLOUD-18528](https://issues.redhat.com/browse/RHCLOUD-18528)
[RHCLOUD-18529](https://issues.redhat.com/browse/RHCLOUD-18529)

## Why?
Part of EBS to OrgID migration

## How?
Added an additional migration step

## Testing
No tests added

## Anything Else?
Any other notes about the PR that would be useful for the reviewer. 

## Secure Coding Practices Checklist Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
21758775-4bfe-49a3-992c-c89da8886c06
960af28a-ee93-4db4-aa98-3d208d140c3f
b2147b03-8087-4fb9-976b-f1bb61fd616f
de2eda87-b4cf-41df-bf41-22f71ee3b631

**Comment by CodyWMitchell** [comment]
@dehort I'm not sure if this is more complicated than changing the fields in the migration. Is there something else that needs to be done here?

**Review by dehort — CHANGES_REQUESTED** [review]
Hey @CodyWMitchell, in this case, we will have to create a new set of migrations (up and down) to make these changes.  I think you'll need an "ALTER TABLE" statement for each??  Unfortunately, I do not speak fluent SQL so I could be wrong.  :)

Let me know if you get stuck and I'll dig in.

**Review by dehort — APPROVED** [review]
LGTM!

**Pull request merged**
