### PR TITLE
[WIP] Switch to confluent kafka library

### PR DESCRIPTION
**Pull request by SteveHNH**
Switch over to confluent kafka library in order to support
authentication

Signed-off-by: Stephen Adams <stephen.adams@redhat.com>

## What?
Switch to confluent kafka and support authentication

## Why?
Switching over to confluent kafka library gives us what we need to support authentication to kafka servers.

## How?
Switched the consumer and producer logic to be in line with confluent kafka. Had to add a few things related to the ssl stuff for kafka in fedramp and managed kafka. 

## Testing
The tests for this one are all using mocked consumers and producers. Need to test this in ephemeral to really try it out against a kafka service.

## Anything Else?
This is a pretty big PR, but the changes to the producers are largely the same. Ended up just having a global kafka auth config since we're pulling it from clowder and we only do auth on the platform side. If we add some kind of auth to MQTT later, then we might need to do some stuff there. 

## Secure Coding Practices Checklist Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
4656eaab-a396-44f3-ae4f-e338cc76865b
ae139f62-2a01-4e41-8e99-1b8ef0ea280f
d24ab19d-6b99-4d4a-94b2-f906fa0691d5
df36e81e-071d-495a-8d57-d14f94ccd5a3

**Comment by dehort** [comment]
Closing for now.  I've decided to stay with segmentio kafka for a bit longer.

**Pull request closed without merging**
