### PR TITLE
Be more restrictive while building the image

### PR DESCRIPTION
**Pull request by dehort**
## What?
Explain what the change is linking any relevant JIRAs or Issues.

## Why?
Consider what business or engineering goal does this PR achieves.

## How?
Describe how the change is implemented. Any noteable new libaries, APIs, or features.

## Testing
Did you add any tests for the change?

## Anything Else?
Any other notes about the PR that would be useful for the reviewer. 

## Secure Coding Practices Checklist Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Comment by dehort** [comment]
16:01:27 Error response from daemon: Get "https://quay.io/v2/": unauthorized: Could not find robot with username: **** and supplied password.

Not ready yet...

**Review by tahmidefaz — APPROVED** [review]

**Comment by dehort** [comment]
Ok, I think the python mqtt client code changed and this is breaking us.

**Pull request merged**
