### PR TITLE
Add org_id to auth middleware [RHCLOUD-17663] and GetOrgID() to Principal interface [RHCLOUD-17664]

### PR DESCRIPTION
**Pull request by CodyWMitchell**
Added org_id to the auth middleware and created a test for a request with an org_id

### CODE REVIEW

**Comment by CodyWMitchell** [comment]
Hey @dehort, could you check this out and let me know if I'm missing anything here?

**Review by dehort — COMMENTED** [review]
Looking good!  Feel free to add the code for RHCLOUD-17664 into this PR as well.

**Review by dehort — CHANGES_REQUESTED** [review]
@CodyWMitchell Looking good!

Please modify the tests to make sure the org_id is getting set.

Also, it looks like you might need to rebase.  Let's jump on a call tomorrow and we can work through a rebase / merge.

**Comment by dehort** [comment]
@CodyWMitchell BTW, let me know if you'd like discuss the additional tests and we can jump on a call.

**Comment by dehort** [comment]
@CodyWMitchell Looks good to me!  Once we get it rebased, then we should be able to merge it into master.

**Review by dehort — APPROVED** [review]
LGTM!

**Pull request merged**
