### PR TITLE
Design v2 REST interface [RHCLOUD-18524] & [RHCLOUD-17021]

### PR DESCRIPTION
**Pull request by CodyWMitchell**
## What?
Design v2 of the REST interface [[RHCLOUD-18524]](https://issues.redhat.com/browse/RHCLOUD-18524)

- Split of "management" versions "end user" operations
- Replace references of account with org_id
- Replace references of node_id with client_id [[RHCLOUD-17021]](https://issues.redhat.com/browse/RHCLOUD-17021)

## Why?
Part of the migration from EBS account numbers to org_id. Also removes outdated reference to node_id from receptor.

## How?
Added api.spec.v2.json with the required changes.

## Testing
No new tests required

## Anything Else?
Any other notes about the PR that would be useful for the reviewer.

## Secure Coding Practices Checklist Link
https://github.com/RedHatInsights/secure-coding-checklist
Secure Coding Checklist

- [ ]  Input Validation
- [ ]  Output Encoding
- [ ]  Authentication and Password Management
- [ ]  Session Management
- [ ]  Access Control
- [ ]  Cryptographic Practices
- [ ]  Error Handling and Logging
- [ ]  Data Protection
- [ ]  Communication Security
- [ ]  System Configuration
- [ ]  Database Security
- [ ]  File Management
- [ ]  Memory Management
- [ ]  General Coding Practices

### CODE REVIEW

**Comment by CodyWMitchell** [comment]
Hey @dehort, I'm trying to figure out the source of this error I'm getting in the PR build:
`urllib3.exceptions.LocationParseError: Failed to parse: http://none:None/api/ingress/v1/upload`
([Test Result](https://ci.ext.devshift.net/job/RedHatInsights-cloud-connector-pr-check/240/testReport/))

**Comment by CodyWMitchell** [comment]
@dehort We shouldn't need to add any additional tests for these changes until the v2 endpoints are implemented, right?

**Comment by dehort** [comment]
@CodyWMitchell sorry for the delay on this.  I made some minor tweaks (changed the name of the client-id in the path, removed the account number psk header from the v2 calls) and added them to this pr.  Let me know what you think!

**Comment by dehort** [comment]
@jharting would you mind reviewing this?  For the v2 calls, I am looking at removing the explicit passing of the account number.  The "customer" facing v2 calls will be:  POST /v2/connections/{client_id}/message, GET /v2/connections/{client_id}/status and GET /v2/connections.

**Comment by InsightsDroid** [comment]
Test results are available in [Ibutsu](https://url.corp.redhat.com/ibutsu-runs). The test run IDs are:
0113ec58-a053-45c2-8f26-1983d14598cd
1f6c8247-a9a0-4146-b047-3b913a5ac323
5b3ccbbc-320b-46e0-85a2-6fdfc9c984d6
6b932e4c-86db-4a4a-83b2-84190d58bc33

**Pull request merged**
