### PR TITLE
Send a reconnect message to the client when the cert lookup fails and…

### PR DESCRIPTION
**Pull request by dehort**
… when sending host data to inventory fails

### CODE REVIEW

**Comment by mkanoor** [comment]
@dehort Can other services tap into this process to send error messages to the RHCD which it can log. When cloud services send messages via RHCD they are asking for the worker to do something but we don't have a way of sending control errors from the cloud services. We can implement it in the different workers or we can just use this process to send error messages which just have to be logged on the RHCD system so that customer can look at it and react to it.
For example we have

(1) Bad Certificate issue
(2) Entitlement Issues
(3) Error Creating objects in the cloud 

All of these are informational messages to the customer, the RHCD or any of the workers can't do anything about it. It requires customer intervention to resolve the issue. If the certificate is bad or the Source Name is a duplicate the customer can make some changes and then retry the install themselves.

I am wondering if the cloud services can call this API end point
https://github.com/RedHatInsights/cloud-connector/blob/62a12c97c535a13f37529b4b6550952225b0bb9b/internal/controller/api/api.spec.json#L247
and send an error message which the RHCD can log as an error.

Instead of every worker adding a task just to cloud log error messages If we can use the above API and have RHCD do the logging.

**Comment by dehort** [comment]
@mkanoor Are you just looking for a way to pass messages to the RHCD client to be logged?

**Comment by dehort** [comment]
@mkanoor you are wanting to push an error message and have the client disconnect, correct?

**Comment by mkanoor** [comment]
@dehort We just need a message to be logged on the rhc side so that the end user can look at the logs and take some corrective action. Their system is un usable for some reason so they would like to know why. If the /connection/disconnection can take a message it would help us.

**Pull request merged**
